remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: AMPs A New Lens to Understanding the Tiny World of Microbes
description: Authors - Jared Dishman, Jiyong Kim, Erik Pak, Kishan Pansuria
